# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Manic Tablet Shop
email: info@manictablet.com
description: > # this means to ignore newlines until "baseurl:"
  Manic Tablet, Compra, Reparación, Venta y Cursos para productos Apple. Donostia - San Sebastián
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shop.manictablet.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
lang: es_ES
facebook:
  app_id: manictablet
instagram:
  username: manictablet
  user_id: 1459093497
  app_id: ef5cf286140f4046b39652cb8f29d1dd
  access_token: 1459093497.ef5cf28.91e612a8adeb4743b5fc1c96ef830f18

author: manictablet

logo: /assets/logo.svg

openingHours:
  date: Mo-Fr
  mornings: 09:00-13:00
  afternoons: 15:00-20:00
  extra: "Martes: Servicio Técnico a domicilio 15:00-20:00"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
#  - package.json

collections:
  gamas:
    output: true
    permalink: /:title/
  modelos:
    output: true
    permalink: /:title/
  productos:
    output: true
    permalink: /:collection/:path/
  slides:

defaults:
  - scope:
      path: ""
      type: productos
    values:
      layout: producto
      image: "552x370.png"
      seo:
        type: Product
  - scope:
      path: ""
      type: modelos
    values:
      layout: modelo
      image: "552x370.png"
  - scope:
      path: ""
      type: gamas
    values:
      layout: gama
      image: "552x370.png"
